export const LOGIN = "LOGIN"; 
export const SETUSERDATA = "SETUSERDATA"; 

export const SETPOPULAR = "SETPOPULAR"; 
export const SETPLAYING = "SETPLAYING"; 
export const SETFAVOURITE = "SETFAVOURITE"; 

// Series 
export const SETPOPULARSERIES = "SETPOPULARSERIES"; 
export const SETPLAYINGSERIES = "SETPLAYINGSERIES"; 
